version: '3.4'

services:
  # GEMMA ZDS Document Registratie OpenAPI
  drc:
    image: wigo4it/openapi-drc:alpha
    hostname: drc
    ports:
      - "5094:5094"
  # GEMMA BRP Basis Registratie Personen OpenAPI (fake generator)
  brp:
    image: wigo4it/openapi-brp-fake
    hostname: brp
    ports:
      - "5080:5080"
  # Business Process Engine, Rule Engine and Case Management  
  camunda:
    image: camunda/camunda-bpm-platform:latest
    hostname: camunda
    ports:
      - "8080:8080"
  # Intelligent Text Processing, document generator
  itp:
    image: wigo4it/oxmldocgen-api
    hostname: itp
    ports:
      - "5091:5091"
  # SignalR Event hun, websocket event streaming
  signalr-event-hub:
    image: wigo4it/signalr-event-hub
    hostname: signalr-event-hub
    command: [
      "dotnet",
      "signalr-event-hub.dll",
      "REDIS_HOST=redis",
      "SECURITY_KEY=${JWT_PRIVATE_KEY}"
    ]
    depends_on:
      - redis
    ports:
      - "5051:5051"
  # OpenID Identityserver
  identity-server:
    image: wigo4it/identityserver4
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: identity-server
    ports:
      - "5099:80"
  # Redis In Memory Key/Value Store
  redis:
    image: redis
    hostname: redis
    ports: 
      - "6379:6379"
  # MINIO S3 Bucket Storage
  minio:
    image: minio/minio
    hostname: minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9050:9000"
  # IRMA API Server
  irma-api-server:
    image: privacybydesign/irma_api_server
    hostname: irma-api-server
    ports:
      - "8088:8080"
    environment:
      - IRMA_API_CONF_BASE64_JWT_PUBLICKEY=${JWT_PUBLIC_KEY}
      - IRMA_API_CONF_BASE64_JWT_PRIVATEKEY=${JWT_PRIVATE_KEY}
      - IRMA_API_CONF_ENABLE_VERIFICATION=true
      - IRMA_API_CONF_ENABLE_ISSUING=true
      - IRMA_API_CONF_ALLOW_UNSIGNED_ISSUE_REQUESTS=true
      - 'IRMA_API_CONF_AUTHORIZED_IDPS={"wigo4it": ["*"]}'

